{
    releaseBundleVersion
    {
        getVersion(repositoryKey: "release-bundles-v2", name: "guybar-evidence-enablement", version: "16")
        {
            createdBy
            createdAt
            evidenceConnection
            {
                edges
                {
                    cursor
                    node
                    {
                        path
                        name
                        predicateSlug
                        predicate
                    }
                }
            }
            artifactsConnection(first: 13, after:"YXJ0aWZhY3Q6Mw==")
            {
                totalCount
                pageInfo
                {
                    hasNextPage
                    hasPreviousPage
                    startCursor
                    endCursor
                }
                edges
                {
                    cursor
                    node
                    {
                        path
                        name
                        packageType
                        sourceRepositoryPath
                        evidenceConnection(first: 0)
                        {
                            totalCount
                            pageInfo
                            {
                                hasNextPage
                                hasPreviousPage
                                startCursor
                                endCursor
                            }
                            edges
                            {
                                cursor
                                node
                                {
                                    path
                                    name
                                    predicateSlug
                                    predicate
                                }
                            }
                        }
                    }
                }
            }
            fromBuilds
            {
                name
                number
                startedAt
                evidenceConnection
                {
                    edges
                    {
                        node
                        {
                            path
                            name
                            predicateSlug
                            predicate
                        }
                    }
                }
            }
        }
    }
}
